language: elixir
elixir:
  - 1.6.5
otp_release:
  - 20
script:
  - mix compile --warnings-as-errors
  - mix credo --strict
  - mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
