name: CI
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  elixir:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.17", "1.18"]
        otp: ["26", "27"]
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix dialyzer --format github
      - run: mix test --warnings-as-errors
      - run: mix docs --warnings-as-errors
